wpyblog/urls.py
from .views import (
    list_post,
    category_list_post,
    tag_list_post,
    view_post,
    preview_post,
    clear_cache,
)

# Django > 3
try:
    from django.urls import re_path as url
except ImportError:
    from django.conf.urls import url

app_name = "wpyblog"

urlpatterns = [
    url(r"category/(?P<category_id>\d+)/(?P<slug>[-\S]+)/", category_list_post, name="category-post-list"),
    url(r"^tag/(?P<tag_id>\d+)/(?P<slug>[-\S]+)/", tag_list_post, name="tag-post-list"),
    url(r"^(?P<post_id>\d+)/(?P<slug>[-\S]+)/", view_post, name="view-post"),
    url(r"^preview/(?P<post_id>\d+)/", preview_post, name="preview-post"),
    url("^clear/", clear_cache, name="clear-post"),
    url("", list_post, name="blog"),
]

wpyblog/models.py
# models here

wpyblog/views.py
from django.template.response import TemplateResponse
from django.conf import settings
from django.urls import reverse
from django.views.decorators.cache import cache_page
from django.core.cache import cache
from django.http import HttpResponse, Http404
from django.utils.encoding import uri_to_iri
from django.utils import translation

import requests

ONE_HOUR = 60 * 60
HALF_DAY = ONE_HOUR * 12
ONE_DAY = ONE_HOUR * 24
ONE_WEEK = ONE_DAY * 7

timeout = vars(settings._wrapped).get('BLOG_TIMEOUT', 8)

WPYBLOG_CACHE_TABLE = vars(settings._wrapped).get('WPYBLOG_CACHE_TABLE', 'default')

@cache_page(ONE_WEEK, cache=WPYBLOG_CACHE_TABLE)
def list_post(request):
    print("CCCCCCCCCCXXXX")
    return get_post_list(request)

@cache_page(ONE_WEEK, cache=WPYBLOG_CACHE_TABLE)
def category_list_post(request, category_id, slug):
    return get_post_list(request = request, category_id = category_id)

@cache_page(ONE_WEEK, cache=WPYBLOG_CACHE_TABLE)
def tag_list_post(request, tag_id, slug):
    return get_post_list(request = request, tag_id = tag_id)

@cache_page(ONE_WEEK, cache=WPYBLOG_CACHE_TABLE)
def view_post(request, post_id, slug):
    return get_single_post(request, post_id)

# preview draft post
def preview_post(request, post_id):
    return get_single_post(request, post_id)

def get_single_post(request, post_id):
    context = {}

    post = get_post(post_id)
    if post is None:
        raise Http404()

    post = _process_post(post)
    post["slug"] = uri_to_iri(post["slug"])

    author_name = post["_embedded"]["author"][0]["name"]
    post_categories = post["_embedded"]["wp:term"][0]
    post_tags = post["_embedded"]["wp:term"][1]

    context["post"] = post
    context["author_name"] = author_name
    context["post_categories"] = post_categories
    context["post_tags"] = post_tags
    context["categories"] = get_categories(request.LANGUAGE_CODE)

    response = TemplateResponse(request, "wpyblog/view_post.html", context)

    return response

def get_post_list(request, category_id = None, tag_id = None):
    context = {}

    page_number = request.GET.get('page', 1)

    posts_data = get_posts_data(page_number, category_id, tag_id)

    pagination = get_pagination_data(page_number, posts_data["total_pages"], posts_data["count"])

    context["posts"] = posts_data["posts"]
    context["categories"] = get_categories(request.LANGUAGE_CODE)
    context["pagination"] = pagination

    if category_id is not None:
        context['blog_meta_description'] = get_category(category_id).get('description')

    elif tag_id is not None:
        context['blog_meta_description'] = get_tag(tag_id).get('description')

    response = TemplateResponse(request, "wpyblog/post_list.html", context)

    return response         

def _process_post(post):
    current_lang = translation.get_language()
    post["slug"] = uri_to_iri(post["slug"])
    if post["polylang_current_lang"] == "en_US":
        post["polylang_current_lang"] = "en"
    for count, post_trans in enumerate(post["polylang_translations"]):
        if post_trans["locale"] == "en_US":
            post["polylang_translations"][count]["locale"] = "en"
        post["polylang_translations"][count]["slug"] = uri_to_iri(post["polylang_translations"][count]["slug"])
    return post

def get_posts_data(page_number, category_id = None, tag_id = None):
    
    posts_data = {}
    
    posts = []

    url = settings.BLOG_URL + "/wp-json/wp/v2/posts"

    if category_id is not None:
        url = url + "?categories=" + str(category_id)

    if tag_id is not None:
        url = url + "?tags=" + str(tag_id)    

    query_params = {
        'page': page_number,
        'per_page': 9
    }

    response = requests.get(url, query_params, timeout=timeout, auth=get_blog_access())
    
    posts = response.json()
    count = response.headers.get("X-WP-Total")
    total_pages = response.headers.get("X-WP-TotalPages")

    current_lang = translation.get_language()
    def filter_lang(post):
        if post["polylang_current_lang"] == current_lang:
            return True
        return False

    posts_data["posts"] = map(_process_post, posts)
    posts_data["posts"] = list(filter(filter_lang, posts_data["posts"]))
    posts_data["count"] = count
    posts_data["total_pages"] = total_pages
    
    return posts_data

def get_pagination_data(page_number, total_pages, count):

    total_pages = int(total_pages)
    count = int(count)

    pagination_data = {}
    
    prev_link = ''
    next_link = ''

    previous_page_number = int(page_number) - 1
    next_page_number = int(page_number) + 1

    has_previous = False
    has_next = False

    if previous_page_number > 0:
        has_previous = True

    if next_page_number <= total_pages:
        has_next = True

    prev_link = reverse('wpyblog:blog') + "?page=" + str(previous_page_number)
    next_link = reverse('wpyblog:blog') + "?page=" + str(next_page_number)

    pagination_data["previous_page_number"] = previous_page_number
    pagination_data["next_page_number"] = next_page_number
    pagination_data["has_previous"] = has_previous
    pagination_data["has_next"] = has_next
    pagination_data["num_pages"] = total_pages
    pagination_data["count"] = count

    # pagination link
    pagination_data["prev_link"] = prev_link
    pagination_data["next_link"] = next_link

    return pagination_data

def get_post(post_id):

    post = {}

    url = settings.BLOG_URL + "/wp-json/wp/v2/posts/" + str(post_id) + "?_embed"

    response = requests.get(url, timeout=timeout, auth=get_blog_access())
    if response.status_code != 200:
        return None
    post = response.json()

    return post

def get_categories(lang="en"):
    categories = []

    url = settings.BLOG_URL + "/wp-json/wp/v2/categories?hide_empty=1&lang=" + lang

    response = requests.get(url)
    categories = response.json()

    def _process_category(category):
        category["slug"] = uri_to_iri(category["slug"])
        return category

    categories = map(_process_category, categories)

    return categories

def get_category(id, lang="en"):
    url = settings.BLOG_URL + f"/wp-json/wp/v2/categories/{id}?hide_empty=1&lang={lang}"
    response = requests.get(url)
    return response.json()

def get_tag(id, lang="en"):
    url = settings.BLOG_URL + f"/wp-json/wp/v2/tags/{id}?hide_empty=1&lang={lang}"
    response = requests.get(url)
    return response.json()

# return username and password for API Basic Auth
def get_blog_access():
    return (settings.BLOG_USER, settings.BLOG_PASS)

def clear_cache(request):
    cache.clear()
    return HttpResponse('blog cache cleared!')

wpyblog/templates/wpyblog/partials/blog_navigation.html
{% load i18n %}

<div class="flex py-5 mx-3">
  <div class="space-x-7">
    <a class="link-primary text-sm" href="{% url 'wpyblog:blog' %}">{% translate 'All' %}</a>
    {% for category in categories %}
    <a class="link-primary text-sm" href="{% url 'wpyblog:category-post-list' category_id=category.id slug=category.slug %}">{{ category.name }}</a>
    {% endfor %}
  </div>
</div>

wpyblog/templates/wpyblog/post_list.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% load blog_tags %}

{% block title %}{% translate 'GetOTP Blog' %}{% endblock %}

{% block content %}
<section class="bg-cool-gray-50 border-t">
  <div class="max-w-screen-xl px-5 md:px-10 mx-auto">
    <!-- sidebar container -->
    {% include 'wpyblog/partials/blog_navigation.html' %}
    <!-- end sidebar container -->
  </div>
</section>

<!-- content container -->
{% block docs_content %}
<section class="max-w-screen-xl mx-auto px-5 md:px-12">
  <div class="flex flex-wrap -mb-16 -mx-4">
    {% for post in posts %}
    <div class="w-full sm:w-1/2 lg:w-1/3 mb-16 px-4">
      <a href="{% url 'wpyblog:view-post' post_id=post.id slug=post.slug %}">
        <article class="blog-article h-full flex flex-col mt-12 border-b">
          <!-- post thumbnail -->
          <div class="mb-5">
            {% if post.jetpack_featured_media_url and post.jetpack_featured_media_url.strip %}
            <img src="{{ post.jetpack_featured_media_url }}" alt="{{ post.title.rendered|safe }}" class="object-cover w-full h-64 md:h-56 rounded border">
            {% else %}
            <img src="{% static 'getotp-thumbnail.png' %}" alt="{{ post.title.rendered|safe }}" class="object-cover w-full h-64 md:h-56 rounded border">
            {% endif %}
          </div>
          <!-- end post thumbnail -->
          <p class="text-gray-400 text-xs mb-1.5">{{ post.date|string_to_date }}</p>
          <h2 class="text-cool-gray-900 block text-2xl font-semibold mb-4">
            {{ post.title.rendered|safe }}
          </h2>
          <!-- post excerpt -->
          <div class="flex-1 text-sm text-cool-gray-500 leading-normal">
            {{ post.excerpt.rendered|safe }}
          </div>
          <!-- end post excerpt -->
        </article>
      </a>
    </div>
    {% endfor %}
  </div>

  <!-- pagination -->
  <div class="text-center space-x-3 mt-28 mb-16">
    {% if pagination.has_previous %}
    <a class="btn btn-secondary btn-md" href="{{ pagination.prev_link }}">< {% translate 'Previous page' %}</a>
    {% endif %}
    {% if pagination.has_next %}
    <a class="btn btn-secondary btn-md" href="{{ pagination.next_link }}">{% translate 'Next page' %} ></a>
    {% endif %}
  </div>
  <!-- end pagination -->
</section>
{% endblock %}
<!-- end content container -->
{% endblock %}

wpyblog/templates/wpyblog/view_post.html
{% extends 'base.html' %}
{% load static %}
{% load blog_tags %}
{% load i18n %}
{% block title %}{{ post.title.rendered|safe }}{% endblock %}

{% block social_meta %}
<meta property="og:type" content="website">
<meta property="og:title" content="{{ post.title.rendered|safe }}">
<meta property="og:description" content="{{ post.excerpt.rendered|striptags }}">
<meta property="og:url" content="{{ request.scheme }}://{{ request.META.HTTP_HOST }}{{ request.get_full_path }}">
<meta property="og:site_name" content="GetOTP">
<meta property="og:image" content="https://otp.dev/static/getotp-og.png">

<meta name="twitter:card" content="summary">
<meta name="twitter:site" content="@getotp">
<meta name="twitter:title" content="{{ post.title.rendered|safe }}">
<meta name="twitter:description" content="{{ post.excerpt.rendered|striptags }}">
<meta name="twitter:image" content="https://otp.dev/static/getotp-twcard.png">
{% endblock %}

{% block content %}
<div class="max-w-4xl mx-auto">
  <section class="text-cool-gray-500 mt-2">
    <article class="mx-auto px-10 pt-8 pb-36 md:pt-12">
      <div class="text-sm flex items-center space-x-3 text-cool-gray-300">
        {% for post_category in post_categories %}
        <p class="category-item">
          <a class="link-primary font-medium" href="{% url 'wpyblog:category-post-list' category_id=post_category.id slug=post_category.slug %}">{{ post_category.name }}</a>
        </p>
        {% endfor %}
      </div>

      <!-- content container -->
      {% block docs_content %}
        <a href="{% url 'wpyblog:view-post' post_id=post.id slug=post.slug %}"><h2 class="text-3xl md:text-4xl font-bold mt-2.5 mb-4 text-primary-900">{{ post.title.rendered|safe }}</h2></a>
        <p class="text-gray-400 text-sm">
          {{ post.date|string_to_date }}
          <span class="px-1.5 font-semibold">·</span>
          {{ author_name }}
        </p>

        <!-- post content -->
        <div class="prose prose-sm md:prose max-w-none md:max-w-none mt-6 pt-10 border-t-2">
          {{ post.content.rendered|safe }}
        </div>
        <!-- end post content -->

        {% if post_tags %}
        <div class="mt-14 bg-cool-gray-50 px-6 py-4 rounded">
          <p class="inline font-medium text-primary-700">{% translate 'Tags' %} :</p>
          {% for post_tag in post_tags %}
          <a href="{% url 'wpyblog:tag-post-list' tag_id=post_tag.id slug=post_tag.slug %}" class="btn-secondary btn-sm btn mx-1 font-medium">{{ post_tag.name }}</a>
          {% endfor %}
        </div>
        {% endif %}

      {% endblock %}
      <!-- end content container -->
    </article>
  </section>
</div>
{% endblock %}